version: '3.8'

networks:
  phongnguyenpuppymvc_network:
    driver: bridge    

services:
  phongnguyenpuppymvcdb:
    container_name: phongnguyenpuppymvcdb
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}

    networks:
      - phongnguyenpuppymvc_network 
    volumes:
      - sql_data:/var/opt/mssql
    hostname: phongnguyenpuppymvcdb
    healthcheck:
      test: ["CMD-SHELL", "echo ok"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
     - .env

  phongnguyenpuppymvc:
    container_name: phongnguyenpuppymvc
    image: ${DOCKER_REGISTRY-}phongnguyenpuppymvc
    build:
      context: ./PhongNguyenPuppy MVC
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ConnectionStrings__PhongNguyenPuppy=${ConnectionStrings__PhongNguyenPuppy}
    volumes:
      - ./PhongNguyenPuppy\ MVC/wwwroot/Hinh/HangHoa:/app/wwwroot/Hinh/HangHoa
    depends_on:
      phongnguyenpuppymvcdb:
        condition: service_healthy
    networks:
      - phongnguyenpuppymvc_network
    env_file:
      - .env
volumes:
  sql_data:
